erver:
  port: 8080
spring:
  application:
    name: jacket-shop-backend
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=JacketShop;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sasql
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: d50d1cab322c6f8ba9d82e8765c5e47b0dde58f4b288b24d07c05eca4458e87e40ef773a02434725d020f35eff4a33e0c83c4addd80ec5a7c7a9239b8d137a59
  access-ttl-ms: 900000
  refresh-ttl-ms: 604800000
  issuer: jacket-shop

logging:
  level:
    org:
      springframework:
        security: DEBUG
